services:
  chrome:
    image: selenium/standalone-chrome:120.0
    platform: linux/amd64
    container_name: marketmates_chrome
    hostname: chrome
    shm_size: 2g
    restart: always
    tmpfs:
      - /tmp
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4444/wd/hub/status" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - marketmates

  redis:
    image: redis:7.2-alpine
    platform: linux/amd64
    container_name: marketmates_redis
    ports:
      - "6379:6379"
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - marketmates

  framework:
    build:
      context: .
      dockerfile: Dockerfile-prod
    container_name: marketmates_framework
    expose:
      - "8000"
      - "8001"
    depends_on:
      chrome:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - static_volume:/static
      - media_volume:/media
    env_file:
      - .env.prod
    restart: always
    command: [ "/entrypoint.sh" ]
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8000/ || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - marketmates

  nginx:
    image: nginx:1.25-alpine
    platform: linux/amd64
    container_name: marketmates_nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      framework:
        condition: service_healthy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
      - static_volume:/static:ro
      - media_volume:/media:ro
    restart: always
    networks:
      - marketmates

volumes:
  static_volume:
  media_volume:

networks:
  marketmates:
    external: true
