services:
    chrome:
        image: selenium/standalone-chrome:latest
        platform: linux/amd64
        container_name: marketmates_chrome
        hostname: chrome
        privileged: true
        shm_size: 2g
        restart: always
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
            interval: 10s
            timeout: 5s
            retries: 3

    redis:
        image: redis:alpine
        platform: linux/amd64
        container_name: marketmates_redis
        ports:
            - "6379:6379"
        restart: always
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 10s
            timeout: 5s
            retries: 3

    framework:
        build:
            context: .
            dockerfile: Dockerfile-prod
        container_name: marketmates_framework
        expose:
            - "8000"
        depends_on:
            chrome:
                condition: service_healthy
            redis:
                condition: service_healthy
        volumes:
            - .:/app
            - static_volume:/static
            - media_volume:/media
        env_file:
            - .env.prod
        restart: always
        command: ["/entrypoint.sh"]
        healthcheck:
            test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
            interval: 10s
            timeout: 5s
            retries: 5

    nginx:
        image: nginx:alpine
        container_name: marketmates_nginx
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            framework:
                condition: service_healthy
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ./certs:/etc/nginx/certs
            - static_volume:/static
            - media_volume:/media
        restart: always

volumes:
    static_volume:
    media_volume:
