FROM python:3.11

# Set environment variables to optimize Python
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Set the working directory
WORKDIR /app

# Copy project files
COPY . /app

# Upgrade pip and install dependencies
RUN pip install --upgrade pip

# Copy the requirements file first (better caching)
COPY requirements.txt /app/

# Install Python dependencies
RUN pip install -r requirements.txt

# Expose the application port
EXPOSE 8000

# Use a script to run multiple processes (Django + Celery)
COPY entrypoint-dev.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Set entrypoint command
ENTRYPOINT ["/entrypoint.sh"]
