# Generated by Django 5.1.6 on 2025-03-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketmates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='designation',
            field=models.CharField(default='CFT', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expert',
            name='rank',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
