# Generated by Django 5.1.6 on 2025-03-06 16:12

import marketmates.models.message
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketmates", "0002_expert_designation_alter_expert_rank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="image",
            field=models.ImageField(
                blank=True,
                max_length=1024,
                null=True,
                upload_to=marketmates.models.message.message_image_upload_path,
            ),
        ),
    ]
