# Generated by Django 4.2.20 on 2025-04-04 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketmates", "0003_alter_message_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expert",
            name="rank",
        ),
    ]
