# Generated by Django 4.2.20 on 2025-04-04 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketmates', '0004_remove_expert_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='was_read',
        ),
    ]
