# Generated by Django 4.2.20 on 2025-04-04 14:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "marketmates",
            "0005_remove_chatroom_capacity_remove_chatroom_is_active_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="status",
        ),
    ]
